### PR TITLE
Fixes some of the type hints

### PR DESCRIPTION
**Pull request by sleekslush**
Adds some more strict type comparisons

### CODE REVIEW

**Review by louisgv — APPROVED** [review]
LGTM 👍

**Comment by goenning** [comment]
@sleekslush @louisgv  It seems like after this change the following code is now typed as `boolean | undefined` instead of just `boolean` for the `value` variable, is this expected?

```ts
const [value] = useStorage("some-key, true)
```

**Comment by louisgv** [comment]
@goenning I think that reflects the actual type more closely, albeit it diverged from the sync useState API

Since storage is an async API, the initial value can be undefined.

**Comment by goenning** [comment]
Isn’t the second param meant to be the default though?

It seems to work that way

**Comment by sleekslush** [comment]
Yea, np. I didn't spend a ton of time on this originally so I'll try to take a deeper look this weekend and fix that issue

**Pull request merged**
